/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#faf8ff",
        "inverse-surface": "#24304b",
        "tertiary-container": "#ffd5d4",
        "on-surface-variant": "#4c4732",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#410009",
        "on-primary-fixed": "#211b00",
        "tertiary-fixed-dim": "#ffb3b3",
        "primary-container": "#ffde00",
        "primary-fixed-dim": "#e3c600",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d9e2ff",
        "primary-fixed": "#ffe24a",
        "surface-container-high": "#e1e8ff",
        "on-primary-container": "#716200",
        "secondary-fixed": "#d9e2ff",
        "on-secondary-fixed-variant": "#204488",
        "on-tertiary": "#ffffff",
        "on-background": "#0e1b35",
        "surface-container-low": "#f1f3ff",
        "secondary-container": "#93b2fd",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#920020",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#b0c6ff",
        "on-primary": "#ffffff",
        "secondary": "#3b5ca1",
        "on-secondary-fixed": "#001944",
        "inverse-primary": "#e3c600",
        "inverse-on-surface": "#edf0ff",
        "outline-variant": "#cfc6ab",
        "on-tertiary-container": "#bb2638",
        "outline": "#7d775f",
        "tertiary": "#b52234",
        "surface-tint": "#6d5e00",
        "surface-container-highest": "#d9e2ff",
        "surface-bright": "#faf8ff",
        "surface-dim": "#ced9fd",
        "background": "#faf8ff",
        "on-error": "#ffffff",
        "surface-container": "#e9edff",
        "on-surface": "#0e1b35",
        "tertiary-fixed": "#ffdad9",
        "on-secondary-container": "#1e4386",
        "primary": "#6d5e00",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#524600",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px",
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "gutter-sm": "1rem",
        "space-xs": "0.25rem",
        "gutter": "1.5rem",
        "space-xl": "2.5rem",
        "margin": "2rem",
        "margin-sm": "1rem",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        display: ["'Plus Jakarta Sans'", "sans-serif"],
      },
      boxShadow: {
        'tactile-sm': '0 2px 0px #1E2A45',
        'tactile': '0 4px 0px #1E2A45',
        'tactile-lg': '0 6px 0px #1E2A45',
        'tactile-press': '0 1px 0px #1E2A45',
      },
    },
  },
  plugins: [],
};
